// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (
    type,
    name,
    created_by
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateChatParams struct {
	Type      string
	Name      pgtype.Text
	CreatedBy pgtype.Int4
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (int32, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Type, arg.Name, arg.CreatedBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createChatUser = `-- name: CreateChatUser :exec
INSERT INTO chats_users (
    chat_id,
    user_id
) VALUES (
    $1, $2
)
`

type CreateChatUserParams struct {
	ChatID int32
	UserID int32
}

func (q *Queries) CreateChatUser(ctx context.Context, arg CreateChatUserParams) error {
	_, err := q.db.Exec(ctx, createChatUser, arg.ChatID, arg.UserID)
	return err
}

const getDirectChatBetweenUsers = `-- name: GetDirectChatBetweenUsers :one
SELECT 
    c.id
FROM chats c
JOIN chats_users cu1 ON cu1.chat_id = c.id
JOIN chats_users cu2 ON cu2.chat_id = c.id
WHERE 
    c.type = 'direct'
    AND cu1.user_id = $1
    AND cu2.user_id = $2
LIMIT 1
`

type GetDirectChatBetweenUsersParams struct {
	UserID   int32
	UserID_2 int32
}

func (q *Queries) GetDirectChatBetweenUsers(ctx context.Context, arg GetDirectChatBetweenUsersParams) (int32, error) {
	row := q.db.QueryRow(ctx, getDirectChatBetweenUsers, arg.UserID, arg.UserID_2)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listChatUsers = `-- name: ListChatUsers :many
SELECT
    cu.user_id,
    u.username
FROM chats_users cu
INNER JOIN users u ON u.id = cu.user_id
WHERE cu.chat_id = $1
`

type ListChatUsersRow struct {
	UserID   int32
	Username string
}

func (q *Queries) ListChatUsers(ctx context.Context, chatID int32) ([]ListChatUsersRow, error) {
	rows, err := q.db.Query(ctx, listChatUsers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatUsersRow
	for rows.Next() {
		var i ListChatUsersRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChats = `-- name: ListUserChats :many
SELECT
    c.id,
    c.type,
    c.name,
    c.created_at,
    (
        SELECT json_agg(row_to_json(t))
        FROM (
            SELECT
                u.id,
                u.username
            FROM chats_users cu
            INNER JOIN users u on cu.user_id = u.id
            WHERE cu.chat_id = c.id
        ) t
    ) chat_users_json,
    (
        SELECT row_to_json(t)
        FROM (
            SELECT 
                m.content,
                m.created_at
            FROM messages m
            WHERE m.chat_id = c.id
            ORDER BY m.created_at DESC
            LIMIT 1
        ) t
    ) last_message_json,
    (
        SELECT COUNT(*)
        FROM messages m
        WHERE 
        m.chat_id = c.id
        AND
        m.read_at IS NULL
        AND
        m.user_id != $1
    ) unread_messages_count
FROM chats c
INNER JOIN chats_users cu ON cu.chat_id = c.id
WHERE 
    cu.user_id = $1
`

type ListUserChatsRow struct {
	ID                  int32
	Type                string
	Name                pgtype.Text
	CreatedAt           pgtype.Timestamptz
	ChatUsersJson       []byte
	LastMessageJson     []byte
	UnreadMessagesCount int64
}

func (q *Queries) ListUserChats(ctx context.Context, userID pgtype.Int4) ([]ListUserChatsRow, error) {
	rows, err := q.db.Query(ctx, listUserChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserChatsRow
	for rows.Next() {
		var i ListUserChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.ChatUsersJson,
			&i.LastMessageJson,
			&i.UnreadMessagesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
