// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (
    id,
    chat_id,
    uploader_id,
    file_key,
    file_name,
    mime_type,
    size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateFileParams struct {
	ID         pgtype.UUID
	ChatID     pgtype.UUID
	UploaderID pgtype.UUID
	FileKey    string
	FileName   string
	MimeType   string
	SizeBytes  int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.ID,
		arg.ChatID,
		arg.UploaderID,
		arg.FileKey,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
	)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT 
    id, 
    chat_id, 
    uploader_id, 
    file_key, 
    file_name, 
    mime_type, 
    size_bytes, 
    updated_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UploaderID,
		&i.FileKey,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.UpdatedAt,
	)
	return i, err
}
