// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    chat_id,
    user_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateMessageParams struct {
	ChatID  pgtype.UUID
	UserID  pgtype.UUID
	Content string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.UserID, arg.Content)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listTopNMessages = `-- name: ListTopNMessages :many
SELECT
    m.id,
    m.user_id,
    m.content,
    m.created_at,
    m.read_at,
    (
        SELECT json_agg(row_to_json(t))
        FROM (
            SELECT  
                f.id,
                f.file_key,
                f.file_name,
                f.mime_type,
                f.size_bytes
            FROM files f
            WHERE f.message_id = m.id
        ) t
    ) files_json
FROM messages m
WHERE m.chat_id = $1
ORDER BY m.created_at
LIMIT $2 OFFSET $3
`

type ListTopNMessagesParams struct {
	ChatID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListTopNMessagesRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
	FilesJson []byte
}

func (q *Queries) ListTopNMessages(ctx context.Context, arg ListTopNMessagesParams) ([]ListTopNMessagesRow, error) {
	rows, err := q.db.Query(ctx, listTopNMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopNMessagesRow
	for rows.Next() {
		var i ListTopNMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.ReadAt,
			&i.FilesJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages m
SET 
    read_at = now()
WHERE 
    m.chat_id = $2
    AND 
    m.user_id != $3
    AND 
    m.read_at IS NULL
    AND
    m.created_at <= (SELECT created_at FROM messages WHERE messages.id = $1)
`

type MarkMessagesAsReadParams struct {
	ID     pgtype.UUID
	ChatID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, arg.ID, arg.ChatID, arg.UserID)
	return err
}
