// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    chat_id,
    user_id,
    content
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id
`

type CreateMessageParams struct {
	ChatID  int32
	UserID  pgtype.Int4
	Content string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.UserID, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTopNMessages = `-- name: ListTopNMessages :many
SELECT
    m.id,
    m.user_id,
    m.content,
    m.created_at
FROM messages m
WHERE m.chat_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTopNMessagesParams struct {
	ChatID int32
	Limit  int32
	Offset int32
}

type ListTopNMessagesRow struct {
	ID        int64
	UserID    pgtype.Int4
	Content   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListTopNMessages(ctx context.Context, arg ListTopNMessagesParams) ([]ListTopNMessagesRow, error) {
	rows, err := q.db.Query(ctx, listTopNMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopNMessagesRow
	for rows.Next() {
		var i ListTopNMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
