// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        pgtype.UUID
	Type      string
	Name      pgtype.Text
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type ChatsUser struct {
	ChatID    pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type File struct {
	ID         pgtype.UUID
	ChatID     pgtype.UUID
	UploaderID pgtype.UUID
	FileKey    string
	FileName   string
	MimeType   string
	SizeBytes  int64
	UpdatedAt  pgtype.Timestamptz
	MessageID  pgtype.UUID
}

type Message struct {
	ID        pgtype.UUID
	ChatID    pgtype.UUID
	UserID    pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
